### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by Joannis** [vapor/vapor#1322]
# The below will be taken care of a different way

I'm working on a command line tool that will highlight these issues and could be linked to unit testing.

## The checklist

- [ ] Updated docs
- [ ] 70% test coverage minimum
- [ ] links to website docs in all public types/functions/variables
- [x] Unnecessary usage of `Container` over `EventLoop`
- [x] Unnecessary `queue.async` dispatches
- [x] Optionals that can have a sensible default
- [x] Remove `fatalError` occurrences
- [x] `TODO` or `FIXME`
- [ ] Review possible APIs that may need to break
  - [x] Move `String` to `URI` where appropriate. URI is `ExpressibleByStringLiteral`
  - [ ] Enums
  - [ ] Public APIs that should be internal
  - [ ] Consistency in the APIs
    - [ ] For example, all `connect` functions look similar/the same
